In [49]:
import cv2
import numpy as np

In [50]:
img = cv2.imread('/content/Dragon.jpeg',0)

In [51]:
gauss = img + np.random.normal(0, 20, img.shape)

In [52]:
print(gauss)

[[ 4.76537133e+01 -1.52755273e+01  4.78759043e+01 ...  1.44102526e+01
   1.05140037e+01  9.66501554e-01]
 [ 3.78017556e+01  1.58713466e+01  3.10427893e+01 ...  3.80921047e+01
   1.07570026e+01 -2.07269082e+01]
 [ 6.76980137e+01  5.32575484e+01  6.38657295e+01 ...  2.33940198e+01
   2.72555150e+01  7.11610046e+00]
 ...
 [ 2.64721976e+02  2.85371488e+02  2.20596277e+02 ...  4.02051286e+01
  -1.29561741e-01  3.27118605e+01]
 [ 2.32043627e+02  2.37671301e+02  2.48675276e+02 ...  3.10724139e+01
   2.18713032e+01 -2.97126062e+00]
 [ 2.62816547e+02  2.41653078e+02  2.38533420e+02 ... -8.73216142e+00
  -8.66677002e-01 -1.66121889e+01]]


In [53]:
gauss = np.clip(gauss,0,255).astype(np.uint8)

In [54]:
print(gauss)

[[ 47   0  47 ...  14  10   0]
 [ 37  15  31 ...  38  10   0]
 [ 67  53  63 ...  23  27   7]
 ...
 [255 255 220 ...  40   0  32]
 [232 237 248 ...  31  21   0]
 [255 241 238 ...   0   0   0]]


In [55]:
sp = img.copy()

In [56]:
prob = 0.02
rand = np.random.rand(*img.shape)
sp[rand<prob]=0

In [57]:
sp[rand>1-prob] = 255

In [58]:
print(rand)

[[0.21940094 0.57566755 0.17827494 ... 0.96107664 0.50413442 0.07102803]
 [0.64302846 0.04203679 0.66602996 ... 0.854243   0.67239525 0.56650012]
 [0.33861878 0.24348477 0.08529934 ... 0.95145477 0.24073923 0.56934998]
 ...
 [0.55553544 0.0186771  0.28482305 ... 0.36514431 0.42225874 0.91815949]
 [0.42992653 0.95838542 0.31284715 ... 0.63523126 0.66037153 0.4044899 ]
 [0.8049207  0.19886396 0.06676313 ... 0.49500244 0.73841769 0.74554724]]


In [59]:
cv2.imwrite("gauss.jpg",gauss)

True

In [60]:
from google.colab import files
files.download('gauss.jpg')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [61]:
cv2.imwrite("sp.jpg",sp)

True

In [62]:
files.download('sp.jpg')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [63]:
mean_filter = cv2.blur(gauss,(3,3))

In [64]:
median_filt = cv2.medianBlur(sp,3)