In [18]:
import cv2
import numpy as np

In [19]:
img = cv2.imread('/content/img.jpg')

In [20]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [21]:
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

In [22]:
h,s,v = cv2.split(hsv)

In [23]:
print(h)

[[152 152 152 ... 118 119 119]
 [152 152 152 ... 118 118 119]
 [152 152 152 ... 118 118 118]
 ...
 [120 120 120 ... 112 112 112]
 [120 120 120 ... 112 112 112]
 [120 120 120 ... 112 112 112]]


In [24]:
print(s)

[[ 83  83  85 ... 173 179 179]
 [ 83  83  83 ... 173 173 179]
 [ 85  83  83 ... 179 179 173]
 ...
 [133 135 135 ... 218 218 218]
 [133 135 135 ... 218 218 218]
 [135 135 135 ... 218 218 218]]


In [25]:
print(v)

[[52 52 51 ... 28 30 30]
 [52 52 52 ... 28 28 30]
 [51 52 52 ... 27 27 28]
 ...
 [50 49 49 ... 48 48 48]
 [50 49 49 ... 48 48 48]
 [49 49 49 ... 48 48 48]]


In [26]:
lower_h = 35
upper_h = 85

In [27]:
mask = cv2.inRange(h, lower_h, upper_h)

In [28]:
result = cv2.bitwise_and(img, img, mask=mask)

In [29]:
cv2.imwrite('result.jpg',result)

True

In [38]:
lower_h2 = 160
upper_h2 = 180

In [39]:
mask2 = cv2.inRange(h, lower_h2, upper_h2)

In [40]:
result2 = cv2.bitwise_and(img, img, mask=mask2)

In [41]:
cv2.imwrite('result2.jpg',result2)

True

In [43]:
lower_h3 = 100
upper_h3 = 130

In [44]:
mask3 = cv2.inRange(h, lower_h3, upper_h3)

In [45]:
result3 = cv2.bitwise_and(img, img, mask=mask3)

In [46]:
cv2.imwrite('result3.jpg',result3)

True

In [48]:
lower_h4 = 10
upper_h4 = 25

In [49]:
mask4 = cv2.inRange(h, lower_h4, upper_h4)

In [50]:
result4 = cv2.bitwise_and(img, img, mask=mask4)

In [51]:
cv2.imwrite('result4.jpg',result4)

True